### ISSUE TITLE
Anomaly sub groups?

### ISSUE THREAD

**Issue by timothyckl** [KevinWangHP/Anomaly-Clustering#2]
In the paper, defective images are clustered into their sub groups like this:

![image](https://github.com/KevinWangHP/Anomaly-Clustering/assets/89766111/53aa8cbe-f8fd-4a86-b4f5-cc99937dfc99)

In your implementation, how is this being done?

**Comment by rishabh-akridata** [comment]
@timothyckl Did you find out how to do this?
